- name: update mysql root password for all root accounts
  mysql_user: name=root host=localhost password={{ root_db_password }}

- name: copy .my.cnf file with root password credentials
  template: src=templates/root/.my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: ensure anonymous users are not in the database
  mysql_user: name='' host=localhost state=absent

- name: remove the test database
  mysql_db: name=test state=absent

- name: create wordpress database
  mysql_db: name={{ wordpress_db_name }} state=present

- name: create wordpress user
  mysql_user: name={{ wordpress_db_user }} password={{ wordpress_db_password }} priv={{ wordpress_db_name }}.*:ALL state=present

- name: reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES

