- name: install mariadb
  yum:
    name: mariadb
    state: latest

- name: install mariadb-server
  yum:
    name: mariadb-server
    state: latest

- name: start mariadb service
  service:
    name: mariadb
    enabled: yes
    state: started
