- name: install php
  yum:
    name: php
    state: latest

- name: install php-mysql
  yum:
    name: php-mysql
    state: latest


- name: install php-fpm
  yum:
    name: php-fpm
    state: latest

- name: start php-fpm
  service:
    name: php-fpm
    enabled: yes
    state: started
